### ISSUE TITLE
[BUG] Translation Fails on TYPO3 v12 (message: 'formality' is not supported for given 'target_lang'.)

### ISSUE THREAD

**Issue by Schwuuuuup** [web-vision/deepltranslate-core#366]
**Describe the bug**
The translation process seams to work normaly, but no actual Translation is created. The Original language is prefixed with the usual [This content is not available in English yet]
Log shows:
Mon, 14 Oct 2024 16:46:14 +0200 [ERROR] request="3f0cb91f7e972" component="WebVision.WvDeepltranslate.Client": Bad request, message: 'formality' is not supported for given 'target_lang'. (0) 
Mon, 14 Oct 2024 16:46:14 +0200 [WARNING] request="3f0cb91f7e972" component="WebVision.WvDeepltranslate.Service.DeeplService": Translation not successful 

**To Reproduce**
Create German content element (languageID=0) in TYPO3 v12.4.21 / wv_deepltranslate 4.3.1
Create English translation (option DeepL (autodetect))

**Expected behavior**
The translated conttent element  should contain English content instead of German original

**TYPO3 Setup**
* TYPO3 Version 12.4.21
* Server (Apache-cgi/Apache-fpm/nginx-fm/other), apache/phpfpm in docker
* Database type and version (SQLite/Postgres/MariaDB/MySQL) MariaDB 10.6.19
* PHP version 8.1.30
* DeepL free or paid API? paid
* composer or classic setup? classic

**Additional context**

**Comment by calien666** [comment]
Hi an thank yu for reporting this bug. We fixed it already in the latest main branch. Could youy check, if the problem with the main exists anymore?

**Comment by Schwuuuuup** [comment]
Due to technical and infrastructure problems we are not able to build the Extension in composer-mode with our setup. Is there a way to get it as a ZIP. We have the newest version from TER and the Problem is still present. I cloned the extension directly from GIThub (main), but this version caused a ton of errors and had to be uninstalled immediately.

**Comment by calien666** [comment]
I'm sorry responding that late. We're currently working on a release, hopefully until the end of the week. As we have changed the formality behaviour and moved it into the language specific site configuration instead of defining formality globally, this bug should be done. For more information take a look into #353

**Comment by calien666** [comment]
As no response is there since three months, I will close this issue. If you think, this is wrong, feel free to leave a comment
